version: '3.9'

services:
  blog:
    image: blog
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "flask run --host 0.0.0.0 --port 5000"]
    ports:
      - 5000:5000
      - 5678:5678
    volumes:
      - .:/app
    environment:
      - FLASK_APP=blog
      - FLASK_DEBUG=True
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
