version: '3.9'

services:
  blog:
    image: blog
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - blog-internal
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - blog-internal

networks:
  blog-internal: